// server.js
import express from 'express';
import cors from 'cors';
import * as snarkjs from 'snarkjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = 3001;

app.use(cors());
app.use(express.json());

// This endpoint now only VERIFIES a proof generated by the client.
app.post('/api/verify', async (req, res) => {
  try {
    const { proof, publicSignals } = req.body;
    console.log("Received proof for verification...");

    // Load the verification key
    const vkeyPath = path.join(__dirname, 'public/verification_key.json');
    const vkey = JSON.parse(fs.readFileSync(vkeyPath));

    // Verify the proof
    const isVerified = await snarkjs.groth16.verify(vkey, publicSignals, proof);

    console.log("Proof verification result:", isVerified);

    if (isVerified) {
      res.json({ verified: true, message: "Proof verified successfully!" });
    } else {
      res.status(400).json({ verified: false, error: "Invalid proof" });
    }

  } catch (err) {
    console.error("Verification failed:", err);
    res.status(500).json({ verified: false, error: "Verification process failed", details: err.message });
  }
});

app.listen(PORT, () => {
  console.log(`Verification API running at http://localhost:${PORT}`);
});

